name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: setup nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: check flake
        run: nix flake check ./dev/setup/

      - name: setup flake
        run: nix develop ./dev/setup/

      - name: lint code
        run: bun run lint
