name: "Test"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: flake check
        run: nix flake check ./dev/setup/

      - name: Step 2
        run: echo "Another step using Nix"

      - name: Step 3
        run: nix-shell -p hello --run "hello"
