name: "ci"
on:
  pull_request:
  push:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Nix
        uses: cachix/install-nix-action@v27
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: check flake
        run: nix flake check ./dev/setup/

      - name: install dependencies
        run: nix develop ./dev/setup --command "bun --cwd=./ install"

      - name: lint code
        run: nix develop ./dev/setup --command "bun --cwd=./ run lint"
